- name: Install required packages
  community.general.homebrew:
    name: "{{ pkg_name }}"
    state: present
    update_homebrew: true
  loop: "{{ macos_pkgs }}"
  loop_control:
    loop_var: pkg_name