# Always perform same generic linux role
- name: 🌌 Cosmonautical Ansible Playbook
  hosts: all
  tasks:
    - ansible.builtin.include_role: 
        name: debug
      when: debug | default(false)
      
    - ansible.builtin.include_role: 
        name: "{{ ansible_facts[distribution| lower] }}"
