- name: Update and Upgrade Apt
  ansible.builtin.apt:
    update_cache: true 
    upgrade: true

- name: Install packages using apt
  ansible.builtin.apt:
    name: "{{ packages.default | select | list }}"
    state: present