- name: 🔄 Perform Nextcloud Syncs
  ansible.builtin.command: 'nextcloudcmd -h \
    --non-interactive 
    --user {{ nextcloud.username }} \
    --password {{ nextcloud.password }} \
    --path "{{ item.remote }}" \
    "{{ item.target }}" \
    {{ nextcloud.url }}'
  loop: "{{ rclone_bisyncs }}"
  when: (rclone_bisyncs is defined) and (rclone_bisyncs | length > 0)