git_repo_dest: "/var/lib" 

packages:
  creator:
    - ardour
    - davinci-resolve
    - krita
    - sonivox
  default:
    - curl
    - "{{ 'fastfetch' if (ansible_facts['distribution'] | lower) == 'nixos' else 'neofetch'}}"
    - fish
    - git
    - nano
    - rclone
    - tmux
    - tree
    - wget
  desktop:
    - appimage-run
    - dracula-theme
    - fantasque-sans-mono
    - firefox
    - "{{ 'gearlever' if (system.unstable | default(false)) }}"
    - "{{ (system.unstable | default(false)) | ternary('gnome-tweaks', 'gnome.gnome-tweaks') }}"
    - google-chrome
    - libimobiledevice
    - usbmuxd
    - mission-center
    - nextcloud-client
    - qFlipper
    - rnote
    - deluge
    - vesktop
  devtool:
    - ansible
    - nodejs_22
    - popsicle
    - "{{ 'zed-editor' if system.unstable }}"
    - warp-terminal
  emulation:
    - dolphin-emu
    - dolphin-emu-primehack
    - mupen64plus
    - rmg-wayland
    - rpcs3
    - ryujinx
    - pcsx2
    - steam-rom-manager
    - xemu
  gaming:
    - clonehero
    - lutris
    - prismlauncher
    - protonplus
    - protontricks
    - steamtinkerlaunch
    - r2modman
    - "{{ 'steam' if not (deck.enabled | default(false)) }}"
    - "{{ 'nexusmods-app-unfree' if (system.unstable | default(false)) }}"
    - "{{ 'lact' if gpu is defined and (gpu.amd | default(false)) }}"
  htpc:
    - kodi-wayland
  media:
    - delfin
    - feishin
    - finamp
    - freetube
    - plexamp
    - spotify