- name: Create Folders
  become: true
  ansible.builtin.file:
    path: "{{ folder_path }}"
    state: directory
    recurse: true
    owner: "{{ users[0].name }}"
    group: "{{ 'staff' if is_macos else 'users'}}"
    mode: "0755"
  loop:
    - "{{ binary_location }}"
    - "{{ temp_location }}"
  loop_control:
    loop_var: folder_path

- name: Download and extract release
  ansible.builtin.unarchive:
    src: "{{ pkg_url }}"
    dest: "{{ temp_location }}"
    remote_src: true

- name: Move binary from temp directory
  ansible.builtin.copy:
    src: "{{ temp_location }}/{{ release_folder_name }}/"
    dest: "{{ binary_location }}"
    remote_src: true
    owner: "{{ users[0].name }}"
    group: "{{ 'staff' if is_macos else 'users'}}"
    mode: "0755"