- name: Include file management
  ansible.builtin.include_tasks: file_management.yml

- name: Gather facts for configuration file
  ansible.builtin.include_tasks: settings_facts.yml

- name: Template and Copy config file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/Settings.json.j2"
    dest: "{{ binary_location }}/Settings.json"
    owner: "{{ users[0].name }}"
    group: "users"
    mode: "0755"

- name: Start ImmichFrame
  ansible.builtin.command:
    cmd: "./Immich_Frame DISPLAY=:0.0"
    chdir: "{{ binary_location }}"