is_macos: "{{ (ansible_system | lower) == 'darwin' }}"

release_folder_name: "ImmichFrame-v{{ release_version }}_-{{ release_type }}-x64"
release_type: "{{ 'osx' if is_macos else (ansible_system | lower) }}"