- name: Add the flathub flatpak repository remote to installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"

- name: "Install and Update Flatpaks"
  community.general.flatpak:
    name: "{{ flatpak_pkgs }}"
    state: present
  when: (flatpak_pkgs is defined) and (flatpak_pkgs | length) > 0 