- name: Register package lists
  ansible.builtin.set_fact:
    "{{ packagelist.key }}_pkg_list": "{{ packagelist.value | select | list | join('\n') }}"
  loop: "{{ packages }}"
  loop_control:
    loop_var: packagelist