- name: Create required directories
  become: true
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
  loop:
    - "{{ configuration_cache_dir }}"
  loop_control:
    loop_var: directory

- name: Find .nix configuration files for caching
  ansible.builtin.find:
    paths: "{{ configuration_dir }}"
    file_type: file
    patterns: "*.nix"
    recurse: false
  register: nixos_configuration

- name: Cache .nix configuration files for rollback if needed
  become: true
  ansible.builtin.copy:
    src: "{{ file.path }}"
    dest: "{{ configuration_cache_dir }}/{{ file.path | basename }}"
    remote_src: true
  loop: "{{ nixos_configuration.files }}"
  loop_control:
    loop_var: "file"