- name: "Clone and pull Linux Surface repo"
  become: true
  ansible.builtin.git:
    repo: "{{ repos.linux_surface }}"
    dest: "{{ git_repo_dest }}/linux-surface"
    update: "{{ upgrade | default(false) }}"
    force: true
  when: is_surface_device