deck: # Imports Jovian Experiment archive and adds gaming packages
  enabled: false
  htpc: false
  # 'gaming: true' is implied by enabling the deck setting
desktop: # Adds on productivity suite and dev tool packages
  enabled: false
  gaming: false
  
jovian:
  sha: "19a5x2v06dqdx5qvj6kv2141hky1pgfxjxik6xa4dxjrfjkppjy2"
  revision: "2d050e65a71e02a1f19d1a35c086bd2e3dfb2cdb"
  
git_repo_dest: "/var/lib" 

default_pkgs:
  - "curl"
  - "tmux"
  - "fish"
  - "nano"
  - "wget"
  - "fastfetch"
  - "ls"
  - "python3Full" # Needed for ansible to work

packages:
  gaming:
    - clonehero
    - discord
    - lutris
    - prismlauncher
    - protonplus
    - protontricks
    - steamtinkerlaunch
    - r2modman
    - "{{ 'steam' if not deck.enabled }}"
    - "{{ 'nexusmods-app-unfree' if system.unstable }}"
  htpc:
  - kodi-wayland

users:
  - name: "violet"
    description: "Violet Rose Caulfield"
    normal_user: true
    super_user: true
    extra_groups:
      - "wheel"
      - "docker"
      - "networkmanager"
    packages:
      - "fantasque-sans-mono"

