deck: # Imports Jovian Experiment archive and adds gaming packages
  enabled: false
  htpc: false
  # 'gaming: true' is implied by enabling the deck setting
desktop: # Adds on productivity suite and dev tool packages
  enabled: false
  gaming: false
  
jovian:
  sha: "060j2bf2csa6i3lpglnxnlkph3snp31han9yzrahgc9i17l0680i"
  revision: "faf4c746c068dd8e41b1fa5f18beeabd34d4064c"
  
git_repo_dest: "/var/lib" 

packages:
  default:
    - curl
    - fastfetch
    - fish
    - git
    - nano
    - rclone
    - tmux
    - wget
  desktop:
    - appimage-run
    - ardour
    - dracula-theme
    - fantasque-sans-mono
    - firefox
    - "{{ 'gearlever' if system.unstable }}"
    - "{{ system.unstable | ternary('gnome-tweaks', 'gnome.gnome-tweaks') }}"
    - google-chrome
    - krita
    - mission-center
    - nextcloud-client
    - plexamp
    - popsicle
    - qFlipper
    - rnote
    - spotify
    - transmission_4
    - vesktop
    - warp-terminal
  emulation:
    - dolphin-emu
    - dolphin-emu-primehack
    - rpcs3
    - ryujinx
    - pcsx2
    - steam-rom-manager
    - xemu
  gaming:
    - clonehero
    - lutris
    - prismlauncher
    - protonplus
    - protontricks
    - steamtinkerlaunch
    - r2modman
    - "{{ 'steam' if not deck.enabled }}"
    - "{{ 'nexusmods-app-unfree' if system.unstable }}"
    - "{{ 'lact' if gpu is defined and (gpu.amd | default(false)) }}"
  htpc:
  - kodi-wayland

users:
  - name: "violet"
    description: "Violet Rose Caulfield"
    normal_user: true
    super_user: true
    extra_groups:
      - "wheel"
      - "docker"
      - "networkmanager"
    packages:
      - "fantasque-sans-mono"

