deck: # Imports Jovian Experiment archive and adds gaming packages
  enabled: false
  htpc: false
  # 'gaming: true' is implied by enabling the deck setting
desktop: # Adds on productivity suite and dev tool packages
  enabled: false
  gaming: false
  
jovian:
  revision: "bba994424596df09228f5437bcf8ef7fde1fe56e"
  sha: "13a9l3c6jh6iraz5l2nfyd5m6wmr9kimby73sl8kk5pgkrrlbw92"
  
git_repo_dest: "/var/lib" 

users:
  violet:
    description: "Violet Rose Caulfield"
    isNormalUser: true
    isSuperUser: true
    packages: [
      "dracula-theme",
      "fantasque-sans-mono",
      "firefox",
      "ungoogled-chromium",
      "ardour",
      "plexamp",
      "spotify",
      "vlc",
      "rnote",
      "krita",
      "apostrophe",
      "qFlipper",
      "transmission",
      "deluge",
      "discord",
      "prismlauncher",
      "popsicle",
      "warp-terminal",
      "gnome.gnome-tweaks",
      "gnome-extension-manager",
      "gnomeExtensions.compiz-windows-effect",
      "gnomeExtensions.dash-to-dock",
      "go",
      "nodejs_20",
      "typescript",
      "nodePackages.expo-cli",
      "starship",
      "vscode-with-extensions",
      "vscode-extensions.redhat.ansible",
      "vscode-extensions.redhat.java",
      "vscode-extensions.redhat.vscode-yaml",
      "vscode-extensions.svelte.svelte-vscode",
      "vscode-extensions.dracula-theme.theme-dracula"
    ]