deck: # Imports Jovian Experiment archive and adds gaming packages
  enabled: false
  htpc: false
  # 'gaming: true' is implied by enabling the deck setting
desktop: # Adds on productivity suite and dev tool packages
  enabled: false
  gaming: false
  
jovian:
  revision: "bba994424596df09228f5437bcf8ef7fde1fe56e"
  sha: "13a9l3c6jh6iraz5l2nfyd5m6wmr9kimby73sl8kk5pgkrrlbw92"
  
git_repo_dest: "/var/lib" 

users:
  - name: "violet"
    description: "Violet Rose Caulfield"
    normal_user: true
    super_user: true
    extra_groups:
      - "wheel"
      - "docker"
      - "networkmanager"
    packages:
      - "fantasque-sans-mono"
