deck: # Imports Jovian Experiment archive and adds gaming packages
  enabled: false
  htpc: false
  # 'gaming: true' is implied by enabling the deck setting
desktop: # Adds on productivity suite and dev tool packages
  enabled: false
  gaming: false
  
jovian:
  sha: "0h4mic8a8krj9h93kbv42ip3972j3hlxdm0a2k6ffbzgrjgkfvy4"
  revision: "ce8ea310530c77b112fda3c88cb1f57e78823467"
  
git_repo_dest: "/var/lib" 

linux_surface_revision: "bbf9548e3309fd226e729db53584fa0bf229a425"
