deck: # Imports Jovian Experiment archive and adds gaming packages
  enabled: false
  htpc: false
  # 'gaming: true' is implied by enabling the deck setting
desktop: # Adds on productivity suite and dev tool packages
  enabled: false
  gaming: false
  
jovian:
  sha: "0h4mic8a8krj9h93kbv42ip3972j3hlxdm0a2k6ffbzgrjgkfvy4"
  revision: "03aa054340528d300711253a98f7dccca9378604"
  
git_repo_dest: "/var/lib" 

linux_surface_revision: "bbf9548e3309fd226e729db53584fa0bf229a425"
