# Always perform same generic linux role
- name: 🌌 Cosmonautical Ansible Playbook
  hosts: all
  tasks:
    - ansible.builtin.include_role: 
        name: ../roles/debug
      when: debug | default(false)
      
    - ansible.builtin.include_role: 
        name: "../roles/{{ ansible_facts['distribution'] | lower }}"
        
    - ansible.builtin.include_role:
        name: ../roles/flatpak 
