os_version:
  stable: '24.05'
  unstable: 'unstable'
  
system:
  state_version: "{{ deck.enabled | ternary(os_version.unstable, os_version.stable) }}"
  unstable: "{{ deck.enabled }}"
  
repos:
  linux_surface: "https://github.com/linux-surface/linux-surface.git"
  
  
jovian:
  revision: "fdcaab38857f221eea20a0073f891feb36ea8e99"
  checksum: "0ksjd2brpr73yyzj8ff9w1xcfwrgvg0yygqpbdh09iwn09hag89a"