configuration_dir: "/etc/nixos"
configuration_cache_dir: "/tmp/nixos"

os_version:
  stable: '24.05'
  unstable: 'unstable'
  
repos:
  linux_surface: "https://github.com/linux-surface/linux-surface.git"

install_creator_packages: "{{ desktop.enabled and (desktop.creator | default(false)) }}"
install_desktop_packages: "{{ desktop.enabled }}"
install_devtool_packages: "{{ desktop.enabled }}"
install_htpc_packages: "{{ deck.enabled and deck.htpc }}"
install_gaming_packages: "{{ deck.enabled or (desktop.gaming | default(false)) }}"
install_media_packages: "{{ (deck.enabled and deck.htpc) or desktop.enabled }}"
install_productivity_packages: "{{ desktop.enabled and (desktop.productivity | default(false)) }}"

is_surface_device: "{{ ansible_system_vendor == 'Microsoft Corporation' }}"
is_unstable: "{{ deck.enabled or is_surface_device or (unstable_channel | default(false)) }}"

system:
  state_version: "{{ is_unstable | ternary(os_version.unstable, os_version.stable) }}"
  unstable: "{{ is_unstable }}"